name: Auto Commit with ver.txt

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  update-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version message
        id: get_ver
        run: |
          ver_msg=$(cat ver.txt)
          echo "VER_MESSAGE=$ver_msg" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.email "jensonguffick@yahoo.com"
          git config --global user.name "JensonGuffick"

      - name: Check for Changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Set Commit Message and Push
        run: |
          git commit --amend -m "$VER_MESSAGE"
          git push --force
