name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: Check current directory contents
      - name: Debug Directory Contents
        run: ls -al

      # Fetch deployments from GitHub API
      - name: Fetch Deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl "https://api.github.com/repos/Tenderhooks/tenderhooks.github.io/deployments" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -o deployments.json

      # Debug: Output contents of `deployments.json` for verification
      - name: Debug Deployments JSON
        run: cat deployments.json

      # Extract version information from `deployments.json`
      - name: Extract Version
        id: extract-version
        run: |
          deployment_id=$(jq -r '.[0].id' deployments.json)  # Example: Extract deployment ID
          version="v1.${deployment_id}"  # Example: Format version
          echo "::set-output name=version::${version}"  # Set output variable

      # Update `ver.txt` file with version information
      - name: Update ver.txt
        run: |
          echo "${{ steps.extract-version.outputs.version }}" > ver.txt
          cat ver.txt  # Display ver.txt content for verification

      # Remaining steps as before...
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
